<?php
/**
 * Title: Product story and buying guidance
 * Slug: purple-optimize/product-story
 * Categories: woocommerce
 * Inserter: no
 */
?>
<!-- wp:group {"align":"full","className":"pot-product-story","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull pot-product-story"><!-- wp:group {"align":"wide","className":"pot-story-section","layout":{"type":"constrained","contentSize":"860px"}} --><div class="wp-block-group alignwide pot-story-section"><!-- wp:paragraph {"className":"pot-eyebrow"} --><p class="pot-eyebrow">Designed around you</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Why this product earns its place</h2><!-- /wp:heading --><!-- wp:post-excerpt {"moreText":""} /--><!-- wp:paragraph --><p><a class="pot-return-to-buy-box" href="#pot-product-buy-box">Choose your options</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:columns {"align":"wide","className":"pot-story-section pot-story-grid"} --><div class="wp-block-columns alignwide pot-story-section pot-story-grid"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Who it is for</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Add concise, factual guidance about the customer, occasion, fit, or problem this product is designed for.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">How it is made</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Explain materials, construction, provenance, or another verifiable point of difference.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Care and use</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Give practical sizing, care, use, or maintenance guidance that reduces purchase uncertainty.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"align":"wide","className":"pot-story-section pot-product-details","layout":{"type":"default"}} --><div class="wp-block-group alignwide pot-story-section pot-product-details"><!-- wp:woocommerce/product-details /--><!-- wp:paragraph --><p><a class="pot-return-to-buy-box" href="#pot-product-buy-box">Return to purchase options</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></section><!-- /wp:group -->
