<?php
/**
 * Title: Purple conversion storefront
 * Slug: purple-optimize/storefront-home
 * Categories: featured, woocommerce
 * Template Types: front-page
 */
?>
<!-- wp:group {"align":"full","className":"pot-home-hero","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull pot-home-hero"><!-- wp:columns {"align":"wide","verticalAlignment":"center"} --><div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:paragraph {"className":"pot-eyebrow"} --><p class="pot-eyebrow">Made for everyday life</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Products worth keeping close</h1><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"medium"} --><p class="has-medium-font-size">Thoughtful materials, useful details, and dependable support from browsing through delivery.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/shop/">Shop the collection</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#pot-featured-products">See featured products</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:image {"width":"1058px","height":"710px","sizeSlug":"large","linkDestination":"none","loading":"eager","fetchPriority":"high"} --><figure class="wp-block-image size-large is-resized"><img src="/wp-content/themes/purple/assets/images/orange-sweater-woman-cropped.webp" alt="A person wearing a textured orange sweater" style="width:1058px;height:710px" width="1058" height="710" loading="eager" fetchpriority="high"/></figure><!-- /wp:image --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
<!-- wp:group {"align":"full","className":"pot-trust-strip","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull pot-trust-strip"><!-- wp:columns {"align":"wide"} --><div class="wp-block-columns alignwide"><!-- wp:column --><div class="wp-block-column"><p><strong>Considered materials</strong><br>Clear product information</p></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><p><strong>Helpful delivery guidance</strong><br>Know what to expect</p></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><p><strong>Straightforward returns</strong><br>Policies within easy reach</p></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><p><strong>Real customer support</strong><br>Help when you need it</p></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"pot-category-discovery","layout":{"type":"default"}} --><section class="wp-block-group alignwide pot-category-discovery"><!-- wp:heading --><h2 class="wp-block-heading">Shop by category</h2><!-- /wp:heading --><!-- wp:pattern {"slug":"purple/categories-on-three-columns"} /--></section><!-- /wp:group -->
<!-- wp:group {"anchor":"pot-featured-products","align":"wide","className":"pot-featured-products","layout":{"type":"default"}} --><section id="pot-featured-products" class="wp-block-group alignwide pot-featured-products"><!-- wp:heading --><h2 class="wp-block-heading">Featured products</h2><!-- /wp:heading --><!-- wp:pattern {"slug":"purple/woocommerce-best-sellers"} /--></section><!-- /wp:group -->
<!-- wp:group {"align":"full","className":"pot-brand-story","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull pot-brand-story"><!-- wp:columns {"align":"wide","verticalAlignment":"center"} --><div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column --><div class="wp-block-column"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="/wp-content/themes/purple/assets/images/storytelling-wool.webp" alt="Natural wool fibers"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"pot-eyebrow"} --><p class="pot-eyebrow">Why Purple</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">The details behind every product</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Use this section to explain the real materials, craft, provenance, or product philosophy that helps customers choose with confidence.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"pot-product-proof","layout":{"type":"default"}} --><section class="wp-block-group alignwide pot-product-proof"><!-- wp:heading --><h2 class="wp-block-heading">What customers are saying</h2><!-- /wp:heading --><!-- wp:pattern {"slug":"purple/reviews-three-columns"} /--></section><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"pot-home-faq","layout":{"type":"constrained","contentSize":"780px"}} --><section class="wp-block-group alignwide pot-home-faq"><!-- wp:heading --><h2 class="wp-block-heading">Questions before you choose?</h2><!-- /wp:heading --><!-- wp:pattern {"slug":"purple/about-faq-question-list"} /--></section><!-- /wp:group -->
